on:
  github:
    branches:
      only: main

jobs:
  CloneRepo:
    resources:
      instance-type: C3
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/AliaksandrSiarohin/first-order-model.git
      path: /outputs/repo
  DownloadWeights:
    resources:
      instance-type: C3
    outputs:
      weights:
        type: dataset
        with:
          ref: vox-adv-cpk
    uses: script@v1
    with:
      script: |-
        pip install gdown 
        gdown https://drive.google.com/uc?id=1L8P-hpBhZi8Q_1vP2KlQ4N6dvlzpYBvZ -O /outputs/weights/vox.pt
      image: python:3.8
  RunModel:
    resources:
      instance-type: P5000
    needs:
      - DownloadWeights
      - CloneRepo
    inputs:
      weights: DownloadWeights.outputs.weights
      repo: CloneRepo.outputs.repo
    uses: script@v1
    with:
      script: |-
        cp -r /inputs/repo/ repo/
        cp /inputs/weights/vox.pt repo/vox.pt
        cd repo/
        python -m pip install \
          https://download.pytorch.org/whl/cu100/torch-1.0.0-cp36-cp36m-linux_x86_64.whl \
          -r requirements.txt
      image: nvcr.io/nvidia/cuda:10.0-cudnn7-runtime-ubuntu18.04
  # PreprocessVideos: pass
  # GenerateAdoro:
  #   resources:
  #     instance-type: P5000
  #   outputs:
  #     image:
  #       type: dataset
  #   uses: script@v1
  #   with:
  #     image:

  # # One preparing job per driving video
  # PrepareVideo1:
  #   inputs:
  #     repo: CloneRepo.outputs.repo
  #   outputs:
  #     artifacts:
  #       type: volume
  #   # RUN THE PREPROCESSING FOR KEYFRAMES FOR A VIDEO
  #   uses: "" # Dockerfile
  #   with:
  #     script:
  #     image:
