on:
  github:
    branches:
      only: main

jobs:
  CloneRepo:
    resources:
      instance-type: C3
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/AliaksandrSiarohin/first-order-model.git
      path: /outputs/repo
  DownloadWeights:
    resources:
      instance-type: C3
    outputs:
      weights:
        type: dataset
    uses: script@v1
    with:
      script: |-
        pip install gdown 
        python -m gdown https://drive.google.com/uc?id=1L8P-hpBhZi8Q_1vP2KlQ4N6dvlzpYBvZ > /outputs/weights/vox.pt
      image: python:3.8
  # PreprocessVideos: pass
  # GenerateAdoro:
  #   resources:
  #     instance-type: P5000
  #   outputs:
  #     image:
  #       type: dataset
  #   uses: script@v1
  #   with:
  #     image:

  # # One preparing job per driving video
  # PrepareVideo1:
  #   inputs:
  #     repo: CloneRepo.outputs.repo
  #   outputs:
  #     artifacts:
  #       type: volume
  #   # RUN THE PREPROCESSING FOR KEYFRAMES FOR A VIDEO
  #   uses: "" # Dockerfile
  #   with:
  #     script:
  #     image:
